### ISSUE TITLE
User registration fails due Bcrypt

### ISSUE THREAD

**Issue by olivierobert** [teerapatxtop/nimble#1]
## Expected

A user should be able to register using an email and a password with 12 characters.

## Actual

The registration fails with this error in local environment:

![image](https://user-images.githubusercontent.com/696529/127804986-5de4db1c-d580-4355-afd9-c901b0435850.png)

I have tried using both Elixir versions 1.12.x (OTP 24.x) and 1.11.x. (OTP 23.2.x)

## Steps to reproduce

- Go to http://localhost:4000/users/register
- Register with the email `olivier@nimblehq.co` and password `123456789123`

## Notes

In any case, it is crucial to set Elixir and Erlan/OTP version either in the README or using dot file configustion e.g. `.tool-versions` (when using [asdf](http://asdf-vm.com/))

**Comment by teerapatxtop** [comment]
Hi,

I could not reproduce the issue on my local machine.
- macOS 11
- Elixir 1.12.1 (compiled with Erlang/OTP 24)
- Phoenix 1.5.9

Could you please try running "mix do deps.get, deps.compile" to see whether it works? Thank you.

Best Regards

**Comment by olivierobert** [comment]
Knowing the versions with which you built the application, I looked at other avenues for errors. I found an issue in the path for the application. The parent directory in which I cloned the project had a space ` ` in its name thus causing BCrypt to fail 🙃 

I do recommend adding the following as pre-requisite in the README to run the application:

```
elixir 1.12.1-otp-24
erlang 24.0.1
```
